repository: Canardoux/danku/en/doc

output: web
# this property is useful for conditional filtering of content that is separate from the PDF.

topnav_title: Dank u Documentation
# this appears on the top navigation bar next to the home button

site_title: The Dank u Documentation
# this appears in the html browser tab for the site title (seen mostly by search engines, not users)

company_name: Canardoux
# this appears in the footer

github_editme_path: Canardoux/danku/tree/master/doc/en/
# if you're using Github, provide the basepath to the branch you've created for reviews, following the sample here. if not, leave this value blank.



host: 127.0.0.1
# the preview server used. Leave as is.

port: 4000
# the port where the preview is rendered. You can leave this as is unless you have other Jekyll builds using this same port that might cause conflicts. in that case, use another port such as 4006.



feedback_email: larpoux@canardoux.xyz

# if you uncomment the previous line, it changes where the feedback link points to

DANKU_VERSION: 0.0.2


highlighter: rouge
# library used for syntax highlighting

markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge


defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: false
      # if you don't want to use Commento.io and just hide comments, change true to false wherever you see the comments property
      search: true
      sidebar: other
      topnav: topnav

sidebars:
- other

description: "This"
